# SPDX-FileCopyrightText: 2026 Cameron Brooks
# SPDX-License-Identifier: GPL-3.0-only
"""Write src/dsp/FittedConstants.hpp from fit/data/constants.json: the complete calibration table (every fitted field over the
priors for any field no stage has written), with the layout hash of the C++ field table so a header for another layout is refused.
usage: python3 fit/make_constants.py          write the header
       python3 fit/make_constants.py --check  exit 1 if the header on disk differs from what constants.json would produce"""
import os, sys, json
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import MODEL, load_cal, DATA  # noqa: E402

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
OUT = os.path.join(ROOT, "src", "dsp", "FittedConstants.hpp")
SRC = os.path.join(DATA, "constants.json")


def render():
    cal = load_cal(SRC)   # raises on any field the engine's layout does not have, or with the wrong count
    d = json.load(open(SRC))
    fitted = set(d["values"].keys())
    ref = d.get("reference", {})
    notes = d.get("notes", {})
    L = []
    L.append("// SPDX-FileCopyrightText: 2026 Cameron Brooks")
    L.append("// SPDX-License-Identifier: GPL-3.0-only")
    L.append("//")
    L.append("// GENERATED by fit/make_constants.py from fit/data/constants.json. Do not edit; rerun the fit (fit/run_all.py) instead.")
    L.append(f"// Reference: {ref.get('reference', '?')} {ref.get('version', '?')} (sha256 {ref.get('sha256', '?')})")
    for k in sorted(notes):
        L.append(f"// {k}: {notes[k]}")
    unfitted = [n for n in MODEL.fields if n not in fitted]
    if unfitted:
        L.append("// fields still at their priors (no stage has written them): " + ", ".join(unfitted))
    L.append("#pragma once")
    L.append("#include <cstdint>")
    L.append("#define HVMC_FITTED_CONSTANTS 1")
    L.append("namespace hvmc {")
    L.append(f"static constexpr uint64_t kFittedLayoutHash = 0x{int(MODEL.layout_hash):016x}ull;")
    L.append(f"static constexpr int kFittedCount = {len(cal)};")
    L.append(f"static const double kFittedValues[{len(cal)}] = {{")
    for name, (off, cnt) in MODEL.fields.items():
        L.append(f"    // {name} [{off}..{off + cnt - 1}]" + ("" if name in fitted else " (prior)"))
        vals = [f"{float(v):.17g}" for v in cal[off:off + cnt]]
        for i in range(0, cnt, 6):
            L.append("    " + ", ".join(vals[i:i + 6]) + ",")
    L.append("};")
    L.append("} // namespace hvmc")
    return "\n".join(L) + "\n"


def main():
    text = render()
    if "--check" in sys.argv:
        old = open(OUT).read() if os.path.exists(OUT) else ""
        if old != text:
            print(f"{os.path.relpath(OUT, ROOT)} is out of date with fit/data/constants.json; run python3 fit/make_constants.py")
            sys.exit(1)
        print(f"{os.path.relpath(OUT, ROOT)} matches fit/data/constants.json")
        return
    open(OUT, "w").write(text)
    print(f"wrote {os.path.relpath(OUT, ROOT)}: {len(load_cal(SRC))} values, layout {int(MODEL.layout_hash):016x}")

if __name__ == "__main__":
    main()
